config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#home'
  resources :posts do
  	collection do
  		get 'feed',to: 'posts/feed'
      get 'recent_posts', to: 'posts/recent_posts'
  	end
  end
  resources :users, only: [:profile] do 
    member do
      get 'profile',to: 'users#profile'
    end
  end
  resources :subscriptions, only: [:create, :destroy, :index]
  resources :users, only: [:index, :show]
  resources :notifications, only: [:index]
  resources :message_notifications, only: [:index]
  resources :conversations, only: [:index, :create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user

	# after_create :create_notification

	def send_notifications
		user = User.find(self.user_id)
		text= "#{user.username} Created a new Post"
		user.inverse_friends.each do |friend|
			Notification.create(user_id: friend.id, notification_text: text)
			notes = friend.notifications.where(seen: false).count
			ActionCable.server.broadcast "room_channel_user_#{friend.id}",
        message: text, count: notes, type: "Notification"
    end
	end

	# def create_notification
	# 	user = User.find(self.user_id)
	# 	text = user.username + " Created a new Post"
	# 	Notification.create(user_id: self.user_id, notification_text: text)
	# end
	# handle_asynchronously :send_notifications
end

app/controllers/posts_controller.rb
require 'irb'
class PostsController < ApplicationController
	before_action :authenticate_user!
	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			flash[:success] = "Post created Successfully"
			@post.send_notifications
			redirect_to posts_path
		else
			flash[:error] = "Error Occured"
			redirect_to posts_path
		end
	end

	def edit
		@post = current_user.posts.find(params[:id])
	end

	def update
		@post = current_user.posts.find(params[:id])
		if @post.update(post_params)
			flash[:success] = "Changes Saved Successfully"
			redirect_to posts_path
		else
			flash[:error] = "Error while updating"
			redirect_to posts_path
		end
	end

	def index
		@posts = current_user.posts.order(created_at: :desc).paginate(page: params[:page], per_page: 6)
	end

	def destroy
		@post = current_user.posts.find(params[:id])
		if @post.destroy
			flash[:success] = "Post Deleted Successfully"
			redirect_to posts_path
		else
			flash[:error] = "Error while Deleting"
			redirect_to posts_path
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def feed
		
		if !params[:page]
			user = current_user
			user.last_drawn_at = Time.now
			user.save
		end
		@posts = Post.where(user_id: current_user.friends.pluck(:id)<< current_user.id).order(created_at: :desc).paginate(page: params[:page], per_page: 6)
	end

	def recent_posts
		user = current_user
		user.last_drawn_at = Time.now
		user.save
		@posts = Post.where(user_id: current_user.friends.pluck(:id)<< current_user.id ).order(created_at: :desc).where("created_at > ?",current_user.last_drawn_at)
	end

	private

		def post_params
			params.require(:post).permit(:id, :content)
		end

end

app/views/posts/_form.html.erb
<%= form_for post do |form| %>
	<%= form.label :content, "content" %>
	<%= form.text_area :content,:class => 'ckeditor'%>
	<%= form.submit "Post" %>
<% end %>

app/views/posts/_posts.html.erb
<% posts.each do |post| %>

	<div class="post-content"> 
		<%= link_to (raw("<i class='fa fa-thumbs-up'></i>")),"",class: 'button post-edit-button' %>
		<%= post.content.html_safe %>
	</div>

<% end %>

app/views/posts/_profile_posts.html.erb
<% @posts.each do |post| %>

	<div class="post-content"> 
		<%= link_to (raw("<i class='fa fa-pencil-square-o'></i>")),edit_post_path(post),class: 'button post-edit-button' %>
		<%= post.content.html_safe %>
	</div>

<% end %>

app/views/posts/edit.html.erb
<%= render partial: 'form', locals: {post: @post} %>

app/views/posts/feed.html.erb
<div id = "new_post_info_container">
	<a href="<%= recent_posts_posts_path%>" data-remote="true">
		<div id = "new_post_info" class="col-sm-offset-5 col-sm-2 hidden">
			<span id ="new_post_count">0</span> new posts
		</div>
	</a>
</div>

<div id = "feed" class = "user_posts col-sm-12">
	<%= render partial: 'posts', locals: {posts: @posts} %>
</div>

<div class="hidden" id="posts-pagination">
  <%= will_paginate @posts %>
</div>

app/views/posts/feed.js.erb
$('#feed.user_posts').append('<%= j render partial: 'posts/posts' ,locals: { posts: @posts } %>')
<% if @posts.next_page %>
  $('#posts-pagination .pagination').replaceWith('<%= j will_paginate @posts %>');
<% else %>
  $('#posts-pagination .pagination').remove();
<% end %>

app/views/posts/index.html.erb
<h4>Your Posts : </h4>

<div id = "user-profile" class = "user_posts col-sm-12">
	<%= render partial: 'profile_posts', locals: {posts: @posts} %>
</div>

<div class="hidden" id="profile-posts-pagination">
  <%= will_paginate @posts %>
</div>

app/views/posts/index.js.erb
$('#user-profile.user_posts').append('<%= j render partial: 'posts/profile_posts' ,locals: { posts: @posts } %>')
<% if @posts.next_page %>
  $('#profile-posts-pagination .pagination').replaceWith('<%= j will_paginate @posts %>');
<% else %>
  $('#profile-posts-pagination .pagination').remove();
<% end %>

app/views/posts/new.html.erb
<%= render partial: 'form', locals: {post: @post} %>

app/views/posts/recent_posts.js.erb
$('#feed.user_posts').prepend('<%= j render partial: 'posts/posts' ,locals: { posts: @posts } %>')

app/views/posts/show.html.erb
<%= @post.content.html_safe %>